apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: httpd:alpine3.19
          name: httpd
          command: ["/bin/bash", "-c"]
          args: ["sleep 5; exit 1"] # sleep for 5 seconds then exit with error
  strategy:
    type: RollingUpdate # default value, for clarity anyways
    rollingUpdate:
      maxUnavailable: 1 # rolling update one by one
      maxSurge: 1 # max number of pods that can be created over the desired number of pods on the deployment (10 for now)
